

GET http://localhost:4000/api/v1/shifttype
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NjBmMGMxNjM3MTdhYjk2OWMyNDg3NyIsImlhdCI6MTcxNzYyOTEyMSwiZXhwIjoxNzI1NDA1MTIxfQ.h_u1lQbzOd1bRhqPO19xyXNQ-r-84i8n3sEM1SmKYC4

###

POST http://localhost:4000/api/v1/shifttype/init
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NjBmMGMxNjM3MTdhYjk2OWMyNDg3NyIsImlhdCI6MTcxNzYyOTEyMSwiZXhwIjoxNzI1NDA1MTIxfQ.h_u1lQbzOd1bRhqPO19xyXNQ-r-84i8n3sEM1SmKYC4
Content-Type: application/json

{
   "shifts":[
        {
             "name":"Longday",
             "startTime":"08:00",
             "endTime":"20:00"
        },
        {
             "name":"Night",
             "startTime":"20:00",
             "endTime":"08:00"
        },
        {
                "name":"Early",
                "startTime":"08:00",
                "endTime":"14:00"
        }
   ]
}


###

DELETE http://localhost:4000/api/v1/shifttype/665f979102c1c21fa6cd8233/6658fcc3b137a3778195779a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NjBmMGMxNjM3MTdhYjk2OWMyNDg3NyIsImlhdCI6MTcxNzYyOTEyMSwiZXhwIjoxNzI1NDA1MTIxfQ.h_u1lQbzOd1bRhqPO19xyXNQ-r-84i8n3sEM1SmKYC4
###

DELETE http://localhost:4000/api/v1/shifttype/6658fcc3b137a3778195779a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NjBmMGMxNjM3MTdhYjk2OWMyNDg3NyIsImlhdCI6MTcxNzYyOTEyMSwiZXhwIjoxNzI1NDA1MTIxfQ.h_u1lQbzOd1bRhqPO19xyXNQ-r-84i8n3sEM1SmKYC4
###
PUT http://localhost:4000/api/v1/shifttype/665fa757562cd4404047beb8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NThmY2MzYjEzN2EzNzc4MTk1Nzc5YSIsImlhdCI6MTcxNzEwNzkwNywiZXhwIjoxNzI0ODgzOTA3fQ.aqKahZkdvAbWCec29BZRlWY0nqB9VBPAK_x_SsL-1fA
Content-Type: application/json

{
    "data":{
        "name":"Longda"
    }
}